projectkatu/katu/urls.py
from django.urls import path
from katu.views import *

urlpatterns = [
    path('', home, name='home'),
    path('noticia/', noticia, name='noticia'),
    path('pacotes/', pacotes, name= 'pacotes'),
    path('contato/', contato, name= 'contato'),
]

projectkatu/projectkatu/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('katu.urls')),
    path('usuarios/', include('usuarios.urls')),
]

projectkatu/usuarios/urls.py
from django.urls import path
from usuarios.views import *

app_name = 'usuarios'

urlpatterns = [
    path('register/', register_view, name = 'register'),
    path('register/<int:firstacess>', register_view, name = 'register'),
    path('register/create', register_create, name = 'create'),
    path("login/", login_view, name = 'login'),
    path("login/acess", login_acess, name = 'acess'),
    path("login/logout", logout_view, name = 'logout'),
    path("area_usuario", area_usuario_view, name = 'area_usuario'),
]

projectkatu/katu/models.py
from django.db import models

# Create your models here.

projectkatu/usuarios/models.py
from django.db import models

# Create your models here.


class Usuarios(models.Model):
    idUsuario = models.BigAutoField(primary_key=True)
    nome = models.CharField(max_length = 300,null=False)
    login = models.CharField(max_length = 45,null=False)
    senha = models.CharField(max_length = 45,null=False)
    cpf = models.CharField(max_length=11, null=False)
    telefone = models.CharField(max_length=15, null=False)
    email = models.CharField(max_length=300,null=True)


    class Meta:
        verbose_name_plural = "Usuários"


    def __str__(self):
        return self.cpf + " - " + self.nome



class Compra(models.Model):
    idCompra = models.BigAutoField(primary_key=True)
    forma_pagamento = models.CharField(max_length=45, null=False)
    data = models.DateField(auto_now_add=True, null=False,
                    help_text="Formato <em> YYYT-MM-DD </em>")
    fk_idUsuario = models.ForeignKey(Usuarios,on_delete= models.CASCADE)


    class Meta:
        verbose_name_plural = "Compra"


    def __str__(self):
        return self.data.strftime("%Y/%m/%d") +" - " + self.forma_pagamento

projectkatu/usuarios/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError

class RegisterForm (forms.ModelForm):
    class Meta:
        model = User
        # fields = '__all__'
        fields = ['first_name', 'username', 'email','password']
        labels = {'first_name' : 'Digite seu nome completo ',
                    'username' : 'Digite seu username',
                    'email' : 'Digite o seu email',
                    'password' : 'Digite sua senha '
                    }
        help_texts = {
            'email' : 'O email deve ter um @',
            'password' : 'crie uma senha forte com caracteres, numeros e simbolos especias',
        }
        error_mensages = {
            'username' : {
                'required' : 'Este campo não pode ser vazio'
            }
        }
        
        widgets = {
            'first_name' : forms.TextInput(attrs ={ 
                'placeholder' : 'Nome Completo',
                'required' : 'true'
        }),
            'password' : forms.PasswordInput(attrs ={
                'placeholder' : 'senha',
            })
        }

    def clean_email(self):
        data = self.cleaned_data.get("email")

        if not '@' in data:
            raise ValidationError(
                'O campo e-mail deve apresentar um @',
                code='invalid'
            )
        
        return data

    def clean(self):
        cleaned_data = super().clean()

        pass1 = cleaned_data.get("password")
        pass2 = cleaned_data.get("password2")

        if pass1 != pass2:
            raise ValidationError(
                {"password" : "Ambos passwords devem ser iguais"}
            )

    email = forms.CharField(
        required = True,
        max_length = 150,
        help_text=(
            'Digite um email valido'
        )
    )

    password2 = forms.CharField(required=True,
        label= 'Repita sua Senha',    
        widget = forms.PasswordInput(attrs ={
            'placeholder' : 'senha',  
        })                     
    )

class AcessForm(forms.Form):
    username = forms.CharField(
        label ='Digite seu username'
    )
    password = forms.CharField(
        label= 'Digite sua Senha',
        widget = forms.PasswordInput()
    )

projectkatu/katu/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.

def home(request):
    return render(request, 'home.html')

def pacotes(request):
    return render(request, 'pacotes.html')

def noticia(request):
    return render(request, 'noticia.html')

def contato(request):
    return render(request, 'contato.html')

projectkatu/usuarios/views.py
from django.shortcuts import render ,redirect
from .forms import RegisterForm ,AcessForm
from django.http import Http404
from django.http import HttpRequest
from django.contrib import messages
from django.contrib.auth.hashers import make_password
from django.contrib.auth.models import User
from django.contrib.auth.hashers import check_password
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

# Create your views here.

def register_view(request, firstacess=0):

    if firstacess == 1:
        register_form = request.session.get("register_form", None)
        form = RegisterForm(register_form)
    else:
        if request.session.get("register_form"):
            del(request.session["register_form"])
        form = RegisterForm()

    register_form = request.session.get("register_form", None)

    form= RegisterForm()
    return render(request, 'pages/register_view.html', {'form' : form})

def register_create(request):
    if not request.POST:
        raise Http404()
    
    post = request.POST
    request.session["register_form"] = post

    form = RegisterForm(post)

    if form.is_valid():
        form.save()
        user = form.save(commit=False)
        user.set_password(user.password)
        user.save()
        messages.success(request, "Usuario cadastrado com sucesso")
        del(request.session["register_form"])
    
    return redirect('usuarios:register', firstacess=1)



def login_view(request):
    if request.POST:
        form_data = request.POST
        form = AcessForm(form_data)
    else:
        form = AcessForm()

    return render(request, 'pages/login_view.html',{'form':form} )

def login_acess(request):

    if not request.POST:
        raise Http404()
    
    post = request.POST

    form = AcessForm(post)

    if form.is_valid():
        usern = post['username']
        passwd = post['password']

        user = User.objects.filter(username = usern)

        if user:
            check_p = check_password(passwd, user[0].password)
            authenticad_user = authenticate(username =usern, password= passwd)
            if check_p:
                messages.success(request, 'Usuario Logado com Sucesso.')
                login(request, authenticad_user)
                return redirect('usuarios:area_usuario')
            else:
                messages.error(request, 'Login e senha não conferem.')
        else:
            messages.error(request, 'Login e senha não conferem.')
    else:
        messages.error(request,'Dados do formulario invalidos' )
   
    return redirect('usuarios:login')

@login_required(login_url ='usuarios : login', redirect_field_name = 'next')
def area_usuario_view(request):

    return render(request, 'pages/area_usuario_view.html')

@login_required(login_url ='usuarios : login', redirect_field_name = 'next')
def logout_view(request):
    if not request.POST:
        redirect('usuarios:login')

    logout(request)

    return redirect('usuarios:login')

projectkatu/katu/templates/cardsDePacotes.html
<div class="main-container">
    <!-- // card 1 -->
    <div class="tour-cards">
        <div class="image-box">
            <img src="https://images.unsplash.com/photo-1602617638731-20cd9c6e92ac?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=897&q=80"
                alt="Blue Lagoon">
            <div class="overlay"></div>
            <div class="image-box-text">
                <h2>Blue Lagoon</h2>
                <p>Beach Resort</p>
            </div>

        </div>
        <div class="tour-cards-text">
            <h1>Blue Lagoon 1 Week Trip </h1>
            <p>A Week long trip around the iceland with a tour of the most famous sights of the island of
                sages.The Blue Lagoon is a geothermal spa in southwestern Iceland. The spa is located in a
                lava field near Grindavík and in
                front of Mount Þorbjörn on Reykjanes Peninsula, in a location favourable for geothermal
                power, and is supplied by water
                used in the nearby Svartsengi geothermal power station.</p>
            <a href="#" class="btn-map">
                <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24"
                    stroke="currentColor" stroke-width="2">
                    <path stroke-linecap="round" stroke-linejoin="round"
                        d="M17.657 16.657L13.414 20.9a1.998 1.998 0 01-2.827 0l-4.244-4.243a8 8 0 1111.314 0z" />
                    <path stroke-linecap="round" stroke-linejoin="round"
                        d="M15 11a3 3 0 11-6 0 3 3 0 016 0z" />
                </svg>
                <span>View Route Map</span>
            </a>
            <div class="price">
                <p>$4540 <span>Per person</span></p>
                <h2>9 Days 18 Nights</h2>
            </div>
        </div>
    </div>

projectkatu/katu/templates/contato.html
{% extends 'master.html' %}

{% load static %}

{% block content %}

       <!-- footer -->
       <footer>
        <div class="footer-image">
            <div class="overlay1"></div>
            <div class="overlay2"></div>

        </div>
        <div class="main-container">
            <div class="heading-foo">
                <img src="" alt="">
                <h1>Catu Experiência</h1>
                <p>Feito com dedicação e carinho</p>
            </div>
            <div class="social-media">
                <h1>Conecte-se Conosco</h1>
                <ul>
                    <li>
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" class="fill">
                            <path
                                d="M9 8h-3v4h3v12h5v-12h3.642l.358-4h-4v-1.667c0-.955.192-1.333 1.115-1.333h2.885v-5h-3.808c-3.596 0-5.192 1.583-5.192 4.615v3.385z" />
                        </svg>
                    </li>
                    <li>
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" class="fill">
                            <path
                                d="M12 2.163c3.204 0 3.584.012 4.85.07 3.252.148 4.771 1.691 4.919 4.919.058 1.265.069 1.645.069 4.849 0 3.205-.012 3.584-.069 4.849-.149 3.225-1.664 4.771-4.919 4.919-1.266.058-1.644.07-4.85.07-3.204 0-3.584-.012-4.849-.07-3.26-.149-4.771-1.699-4.919-4.92-.058-1.265-.07-1.644-.07-4.849 0-3.204.013-3.583.07-4.849.149-3.227 1.664-4.771 4.919-4.919 1.266-.057 1.645-.069 4.849-.069zm0-2.163c-3.259 0-3.667.014-4.947.072-4.358.2-6.78 2.618-6.98 6.98-.059 1.281-.073 1.689-.073 4.948 0 3.259.014 3.668.072 4.948.2 4.358 2.618 6.78 6.98 6.98 1.281.058 1.689.072 4.948.072 3.259 0 3.668-.014 4.948-.072 4.354-.2 6.782-2.618 6.979-6.98.059-1.28.073-1.689.073-4.948 0-3.259-.014-3.667-.072-4.947-.196-4.354-2.617-6.78-6.979-6.98-1.281-.059-1.69-.073-4.949-.073zm0 5.838c-3.403 0-6.162 2.759-6.162 6.162s2.759 6.163 6.162 6.163 6.162-2.759 6.162-6.163c0-3.403-2.759-6.162-6.162-6.162zm0 10.162c-2.209 0-4-1.79-4-4 0-2.209 1.791-4 4-4s4 1.791 4 4c0 2.21-1.791 4-4 4zm6.406-11.845c-.796 0-1.441.645-1.441 1.44s.645 1.44 1.441 1.44c.795 0 1.439-.645 1.439-1.44s-.644-1.44-1.439-1.44z" />
                        </svg>
                    </li>
                    <li>
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" class="fill">
                            <path
                                d="M19.615 3.184c-3.604-.246-11.631-.245-15.23 0-3.897.266-4.356 2.62-4.385 8.816.029 6.185.484 8.549 4.385 8.816 3.6.245 11.626.246 15.23 0 3.897-.266 4.356-2.62 4.385-8.816-.029-6.185-.484-8.549-4.385-8.816zm-10.615 12.816v-8l8 3.993-8 4.007z" />
                        </svg>
                    </li>
                </ul>
            </div>
            <div class="main">
                <h1>Links Diretos</h1>
                <ul>
                    <li><a href="#inicio">Início</a></li>
                    <li><a href="#sobre">Sobre</a></li>
                    <li><a href="#pacotes">Pacotes</a></li>
                    <li><a href="#fotos">Fotos</a></li>
                </ul>
            </div>
            <div class="contact-info">
                <h1>Contatos</h1>
                <div class="contact-info-text">
                    <p>(84) 876236538</p>
                    <p>katuexperiencia@gmail.com</p>
                </div>
            </div>
        </div>
        <div class="credit">
            <h3>By - Full Stack<a href=""> Nossos nomes</a>xxxxxxxxxx</h3>
        </div>
    </footer>
    <!-- ----- -->

    <script src="public/js/main.js"></script>
</body>
{% endblock %}

projectkatu/katu/templates/home.html
{% extends 'master.html' %}

{% load static %}

{% block content %}
<body>


    <!-- main  -->
    <main>

        <!-- banner  -->

        <section class="banner" id="banner" style="background-color: aliceblue;">
            <div class="banner-text">
                <h1>Catu  Experiência</h1>
                <P>Conheça a cultura, paisagem e outros grupos em trilhas e atividades conjuntas.</P>
                
            </div>
            <div class="overlay2">
              
            </div>
        </section>


</body>

</html>

{% endblock %}

projectkatu/katu/templates/master.html
{% load static %}


<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Catu Experiência</title>
    <link rel="shortcut icon" href="" type="image/x-icon">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Dosis:wght@800&family=Poppins:wght@400;500;600;700&display=swap"
        rel="stylesheet">
        <link rel="stylesheet" href=" {% static 'css/forms.css' %} ">
    <!-- css  -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}"> 

</head>
<body>
    <!-- header  -->
    <header class="primary-header">
        <div class="left-part">
            <img src="{% static 'media/logo_KATU_EXPERIÊNCIA.png' %}" alt="">
            <div class="logo" style="color: aliceblue;">
                
                <a href=" {% url 'home' %}"><h1><span>Catu</span> Experiência</h1> </a>
            </div>
        </div>
        <div class="right-part">
            <div class="navbar">
                <ul> 
                    <li><a href="{% url 'pacotes' %}">Pacotes De Turismo</a></li>
                    <li><a href="{% url 'noticia' %}">Feed De Notícias</a></li>
                    <li><a href="{% url 'contato' %}">Sobre</a></li>
                    <li><a href=" {% url 'usuarios:login' %}">Login E Cadastro</a></li>
                </ul>
                <div class="btn-group">
                   
                            <path stroke-linecap="round" stroke-linejoin="round" d="M13 5l7 7-7 7M5 5l7 7-7 7" />
                        
                    </a>
                </div>
            </div>
            <div class="ham-menu">
                <div class="line line-1"></div>
                <div class="line line-2"></div>
                <div class="line line-3"></div>
            </div>
        </div>
    </header>
{% block content %}
{% endblock %}

<footer>
    <!-- Coluna 1 -->
    <div class="column">
        <p style="font-size: 20px;"> Desenvolvedores:</p>
        <p><br> Philipe Muzzi, <br> Marcelo Ryan, <br> Geronilton Oliveira, <br> José Maria</p> 
<br>
        <p>IFRN - Campus Canguaretama</p>
    </div>

</footer>

</html>

projectkatu/katu/templates/noticia.html
{% extends 'master.html' %}

{% load static %}

{% block content %}

     <!-- FEED DE NOTÍCIAS....... PRECISA ADD O JS DE SLIDE (17/06/2023)  -->
     <section class="about" id="about">
        <div class="main-text">
            
            <h1>Feed De Notícias</h1>
            
        </div>
        <div class="main-container">
            <video
                src="https://assets.mixkit.co/videos/preview/mixkit-aerial-view-of-lush-river-valley-and-snowy-mountains-15919-large.mp4"
                autoplay loop muted></video>
        </div>

    </section>

    <!-- tour  -->

</body>

{% endblock %}

projectkatu/katu/templates/pacotes.html
{% extends 'master.html' %}

{% load static %}

{% block content %}
<section class="tour" id="tour">
    <div class="main-text">
        
        <h1>Pacotes e Reservas </h1>
    </div>
    
    {% include 'cardsDePacotes.html'%}
    {% include 'cardsDePacotes.html'%}
    {% include 'cardsDePacotes.html'%}


         
</body>

{% endblock %}

projectkatu/usuarios/templates/pages/area_usuario_view.html
{% extends 'master.html' %}

{% load static %}

{% block content %}
<div class="css-forms">
    <div class="div_titulo-form">
        <h1> Area do Usuario </h1>

        
        {% if messages %}
            {% for message in messages %}
                <div class= "div_sucess">
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}

        <div class="menu-area-usuario">
            <div>
                Voce esta logado como {{ 'request.user.username '}}
            </div>
            <div>
                <form action="{% url 'usuarios:acess' %}" method="post"> 
                    {% csrf_token %}

                    <button type="submit">logout</button>
                </form> 
        </div>
        </div>
    </div>
</div>

{% endblock %}

projectkatu/usuarios/templates/pages/login_view.html
{% extends 'master.html' %}

{% load static %}

{% block content %}

<div class="css-login">
    <div class="div_titulo-form">
        <h1> Login </h1>
      
            <p>
            {% if form.error %}
                <div class= "div_error">
                     o formulario apresenta erros. corrija-los
                </div>  
            {% endif %}

            {% if messages %}
                {% for message in messages %}
                    <div class= "div_sucess">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}
            </p>
        
    </div>

    <div class = "div_login">  
        <form action="{% url 'usuarios:acess' %}" method="post"> 
            {% csrf_token %}

            {% for field in form %}
            <label for="{{ field.id_for_label}}"> {{ field.label }}:</label>
            <br>
            {{field}} <br>

            {% if field.help_text %}
            <div class= "div_helptext">
                {{ field.help_text }}
            </div>
            {% endif %} <br>
            
            {% if field.errors %}
            <div class= "div_error">
                {{ field.errors }}
            </div>
            {% endif %}
            {% endfor %}

            <p><button type ="submit"> Login </button></p>
         </form>   
    </div>
    <div class="div_cadastro">
        <p>Novo Usuario?
        <a href="/usuarios/register" style= "color:red">Cadastrar um Usuario</a>
        </p>
    </div>
</div>

{% endblock %}

projectkatu/usuarios/templates/pages/register_view.html
{% extends 'master.html' %}

{% load static %}

{% block content %}

<div class="css-forms">
    <div>
        <h1>Cadastro de Usuario</h1>

        <p>
            {% if form.error %}
                <div class= "div_error">
                     o formulario apresenta erros. corrija-los
                </div>  
            {% endif %}

            {% if messages %}
                {% for message in messages %}
                    <div class= "div_sucess">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}
        </p>

    </div>
    <div class="div_forms">
        <form action="{% url 'usuarios:create' %}" method="POST">
            {% csrf_token %}
            {% for field in form %}
            <label for="{{field.id_for_label}}"> {{field.label}}</label>
            <br>
            {{field}} <br>
            {% if field.help_text %}
                <div class="div_helptext">
                    {{ field.help_text }}
               </div>
            {%endif%}
            <br>
            {% if field.errors %}
                <div class="div_error">
                    {{ field.errors }}
                </div>
            {% endif %}
            {% endfor %}

            <button type="submit">Salvar</button>
        </form>  
        <div class="div_text">
            <p>Ja tem uma conta?
           <a href=" /usuarios/login" style="color: red">fazer login</a>
            </p>
        </div>
    </div>

</div>



{% endblock %}

templates/Login-Cadastro.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <title>Document</title>
</head>
<body>
    
</body>
</html>

templates/comidas-fotos-localidade.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="index.html">
    <link rel="stylesheet" href="public/sass/style.css">
    <link rel="stylesheet" href="public/sass/style.scss">
    <link rel="stylesheet" href="public/js/main.js">
    <title>Document</title>
</head>
<body>
   
    
      <!-- header  -->
      <header class="primary-header">
        <div class="left-part">
            <img src="public/sass/KATU_EXPERIÊNCIA-removebg-preview.png" alt="">
            <div class="logo" style="color: aliceblue;">
                <h1><span>Catu</span> Experiência</h1>
            </div>
        </div>
        <div class="right-part">
            <div class="navbar">
                <ul>
                    <li><a href="pagina-inicial-empresa.html">Sobre</a></li>
                    <li><a href="link-parte-foto.html">Momentos</a></li>
                    <li><a href="comidas-fotos-localidade.html">Alimentação e Artesanatos</a></li>
                    <li><a href="link-contato.html">Nosso Contato</a></li>
                    <li><a href="feed-de-noticias-empresa.html">Feed De Notícias</a></li>
                    <li><a href="pacotes-reservas.html">Pacotes e Reservas</a></li>
                  
                    <li><a href="#">Login e Cadastro</a></li>
                </ul>
                <div class="btn-group">
                   
                            <path stroke-linecap="round" stroke-linejoin="round" d="M13 5l7 7-7 7M5 5l7 7-7 7" />
                        
                    </a>
                </div>
            </div>
            <div class="ham-menu">
                <div class="line line-1"></div>
                <div class="line line-2"></div>
                <div class="line line-3"></div>
            </div>
        </div>
    </header>

    <section class="media" id="media">
        <div class="main-text">
            
            <h1>Artesanato e Alimentação local</h1>
        </div>
        <div class="main-container">
            <div class="image image-1">
                <img src="https://images.unsplash.com/photo-1617191979724-f755c6d83e01?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=871&q=80"
                    alt="Erupting Volcano">
                <h3>xxxxxxxxxxxxx</h3>
            </div>
            <div class="image image-2">
                <img src="https://images.unsplash.com/photo-1516832970803-325be7a92aa5?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=871&q=80"
                    alt="Icelandic horses ">
                <h3>xxxxxxxxxxxxxxxxxxxxxxx</h3>
            </div>
            <div class="image image-3">
                <img src="https://images.unsplash.com/photo-1489782419474-4d4221dc5b10?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80"
                    alt="Hvítserkur">
                <h3>xxxxxxxxxxxxxxxxx</h3>
            </div>
            <div class="image image-4">
                <img src="https://images.unsplash.com/photo-1540503831458-3237544b2ce5?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1141&q=80"
                    alt="Flatey village">
                <h3>xxxxxxxxxxxxx</h3>
            </div>
            <div class="image image-5">
                <img src="https://images.unsplash.com/photo-1512419180521-2c5585bdf851?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80"
                    alt="Parliament of Puffins">
                <h3>xxxxxxxxxxxxxxxx</h3>
            </div>
            <div class="image image-6">
                <img src="https://images.unsplash.com/photo-1551098955-f124915c1ff3?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80"
                    alt=" Iceland Beach">
                <h3>xxxxxxxxxxxxxxxxxxx</h3>
            </div>
            <div class="image image-7">
                <img src="https://images.unsplash.com/photo-1615130767419-e9ff3afa5a15?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1054&q=80"
                    alt="Reykjavík City">
                <h3>xxxxxxxxxxxxxxxxxx</h3>
            </div>
            <div class="image image-8">
                <img src="https://images.unsplash.com/photo-1477442229003-02551413eaad?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80"
                    alt="Skogafoss Waterfall">
                <h3>xxxxxxxxxxx</h3>
            </div>
            <div class="image image-9">
                <img src="https://images.unsplash.com/photo-1572587356426-b33bf42f999b?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=871&q=80"
                    alt="Iceland Caves">
                <h3>xxxxxxxxxx</h3>
            </div>
            <div class="image image-10">
                <img src="https://images.unsplash.com/photo-1525624160868-97095e12e633?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=869&q=80"
                    alt="Gigjökull">
                <h3>xxxxxxxxxxxxxxxxx</h3>
            </div>
            <div class="image image-11">
                <img src="https://images.unsplash.com/photo-1475518845976-0fd87b7e4e5d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80"
                    alt="Aurora">
                <h3>xxxxxxxxxxxxxxxxxxxxx</h3>
            </div>
            <div class="image image-12">
                <img src="https://images.unsplash.com/photo-1536007379435-ba39ac15caae?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=886&q=80"
                    alt="Solheimasandur Plane Wreck">
                <h3>xxxxxxxxxxxxxxxx</h3>
            </div>
        </div>
    </section>


   

</body>
</html>